services:
  # aplikasi nodejs wa gateway
  gateway4:
    container_name: stie-wa-gateway4
    image: ghcr.io/mfth12/wa-gateway4-stie:latest
    environment:
      - PORT=${PORT}
      - KEY=${KEY}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
    volumes:
      - ./wa_credentials:/wa_credentials
      - ./media:/media
    ports:
      - 8180:8180
    networks:
      - wa-gateway
    restart: always

#setup jaringan
networks:
  wa-gateway:
    driver: bridge
